version: '2.1'

services:

  devopstools-db:
    container_name: devopstools-db
    build: https://github.com/kilerkarol/devopstools_client.git#master:db
    ports:
        - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  devopstools-backend:
    container_name: devopstools-backend
    build: https://github.com/kilerkarol/devopstools_client.git
    environment:
      - APP_SETTINGS=devopstools.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@devopstools-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@devopstools-db:5432/users_test
    ports:
      - 5000:5000
    depends_on:
      devopstools-db:
        condition: service_healthy
    links:
      - devopstools-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
       devopstools-backend:
        condition: service_started
    links:
      - devopstools-backend